### ISSUE TITLE
Add Term Customizer Module

### ISSUE THREAD

**Issue by marta-platoniq** [coopdevs/decidim-coopcat#169]
Can you add Term Customizer module to the Cercles.coop multitenant? 

We need it to customize some literals in meta.cercles.coop, and to develop this proposal: http://cercles.decidim.platoniq.net/assemblies/us-cercles/f/127/proposals/123

Gràcies :)

**Comment by verarojman** [comment]
Added Term Customizer in #190 ;) ❤️
