### ISSUE TITLE
Cooperatives Module

### ISSUE THREAD

**Issue by microstudi** [coopdevs/decidim-coopcat#5]
- [x] Module creation
- [ ] Menus placeholders

Next:

- [ ] Add a new verification method see #1 
- [ ] Vote Delegation #4

**Comment by sauloperez** [comment]
Is there something else you wanted to do here @microstudi ? The work for the specific features is being done in the other issues, including any menus, so I think we can close this.

**Comment by microstudi** [comment]
Yes, this was a very preliminary definition. we can close and work with more detailed issues.
